### ISSUE TITLE
change number of used processor cores 

### ISSUE THREAD

**Issue by helo9** [montagdude/Xoptfoil#1]
Is it possible to controll that number, just like make's -j option?

**Comment by montagdude** [comment]
Yes, you can do it with the OMP_NUM_THREADS environment variable. For example, to use 2 threads -- in bash: 

export OMP_NUM_THREADS=2

In the Windows command prompt:

set OMP_NUM_THREADS=2

**Comment by helo9** [comment]
alright, thanks
