### ISSUE TITLE
Minimum / Maximum range for pitching moment?

### ISSUE THREAD

**Issue by SidusTechnologies** [montagdude/Xoptfoil#3]
I don't know where else to leave this comment. Is there a way to restrict the range of pitching moments? My designs tend to be extremely low drag but over-optimized to the point that they are unstable in pitching moment at stall angles and Reynolds numbers.

**Comment by montagdude** [comment]
There are pitching moment constraints to take care of that. For each operating point, you set:
`moment_constraint_type(n) = setting`
where n is the operating point number and setting can be 'none', 'specify', or 'use_seed'. If you choose 'specify', then you also need to set the min_moment for that point:
`min_moment(n) = value`
where value is the pitching moment coefficient constraint.

By the way, there is a discussion thread on RCGroups. That's how most people ask for help.
[https://www.rcgroups.com/forums/showthread.php?2095696-XoptFoil-airfoil-optimization-with-XFoil](https://www.rcgroups.com/forums/showthread.php?2095696-XoptFoil-airfoil-optimization-with-XFoil)
